### ISSUE TITLE
Slider behaviour

### ISSUE THREAD

**Issue by dglava** [Maato/volumeicon#45]
If the "horizontal slider" option is ticked, which is appropriate for vertical panels, the slider behaves in a weird way. According to the slider the volume is turned all the way up, but it's actually muted and vice versa.

Here's a video example:
http://webmshare.com/6M3GV

The volumeicon version I'm using is 0.5.1, but it also happens in an older (0.4.something) version.

**Comment by Maato** [comment]
That is weird indeed. I think it went unnoticed because for me the blue part of the slider wasn't drawn in previously, making it unclear where the origin of the slider was. If you look in the documentation (https://developer.gnome.org/gtk3/stable/GtkScale.html) you'll see that horizontal sliders are 0 when the blue part is not visible but vertical sliders are 0 when it is, which seems kind of strange to me... Anyway, now in commit 30aa1093a3eb0b60e6bbfe56609c0c73b7f091fe only the vertical slider will be inverted.
